version: '3'
services:
  api:
    image: klemjul/marvelapi:latest
    networks:
      marvelnet:
        ipv4_address: 172.31.0.4
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_USER: root2
        MYSQL_PASSWORD: root2
        MYSQL_ROOT_PASSWORD: Hitachi2019@
      networks:
        marvelnet:
          ipv4_address: 172.31.0.7
      depends_on: 
        - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todoo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root2'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root2'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /storage/docker/marvel/dump:/docker-entrypoint-initdb.d
      - /storage/docker/marvel/db:/var/lib/mysql
    networks:
      marvelnet:
        ipv4_address: 172.31.0.6


  web:
    image: klemjul/marvelweb:latest
    networks:
      marvelnet:
        ipv4_address: 172.31.0.5
networks:
  marvelnet:
    ipam:
      driver: default
      config: 
        - subnet: 172.31.0.0/16